/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Contato.Agenda;
import Contato.Contato;
import Pessoa.Pessoa;
import Pessoa.PessoaFisica;
import Pessoa.PessoaJuridica;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class Principal extends javax.swing.JFrame {

    Agenda agenda = new Agenda();

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtNome = new javax.swing.JTextField();
        LbNome = new javax.swing.JLabel();
        TxtCpfCnpj = new javax.swing.JTextField();
        LbCpfCnpj = new javax.swing.JLabel();
        RdPessoaFisica = new javax.swing.JRadioButton();
        RdPessoaJuridica = new javax.swing.JRadioButton();
        LbTelefone = new javax.swing.JLabel();
        LbEmail = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        BtNovoContato = new javax.swing.JButton();
        BtLimparContato = new javax.swing.JButton();
        BtExcluirContato = new javax.swing.JButton();
        BtSalvaContato = new javax.swing.JButton();
        TxtTelefone = new javax.swing.JTextField();
        JScrollTabelaContato = new javax.swing.JScrollPane();
        TbPessoa = new javax.swing.JTable();
        btAlterar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Pessoa");

        LbNome.setText("Nome");

        LbCpfCnpj.setText("CPF-CNPJ");

        RdPessoaFisica.setText("Pessoa Física");
        RdPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdPessoaFisicaActionPerformed(evt);
            }
        });

        RdPessoaJuridica.setText("Pessoa Jurídica");
        RdPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdPessoaJuridicaActionPerformed(evt);
            }
        });

        LbTelefone.setText("Telefone");

        LbEmail.setText("Email");

        BtNovoContato.setText("Novo");
        BtNovoContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoContatoActionPerformed(evt);
            }
        });

        BtLimparContato.setText("Limpar");
        BtLimparContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimparContatoActionPerformed(evt);
            }
        });

        BtExcluirContato.setText("Excluir");
        BtExcluirContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirContatoActionPerformed(evt);
            }
        });

        BtSalvaContato.setText("Salvar");
        BtSalvaContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvaContatoActionPerformed(evt);
            }
        });

        TbPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telefone", "Email", "Código"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbPessoaMouseClicked(evt);
            }
        });
        TbPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TbPessoaKeyReleased(evt);
            }
        });
        JScrollTabelaContato.setViewportView(TbPessoa);

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RdPessoaFisica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdPessoaJuridica))
                            .addComponent(LbEmail)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TxtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addComponent(TxtEmail, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LbCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtCpfCnpj)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(BtLimparContato)
                                            .addGap(35, 35, 35)
                                            .addComponent(BtExcluirContato))
                                        .addComponent(LbTelefone)
                                        .addComponent(TxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtNovoContato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(btAlterar)
                                .addGap(31, 31, 31)
                                .addComponent(BtSalvaContato)
                                .addGap(187, 187, 187))
                            .addComponent(JScrollTabelaContato, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RdPessoaFisica)
                            .addComponent(RdPessoaJuridica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(LbTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtNovoContato)
                    .addComponent(BtSalvaContato)
                    .addComponent(BtLimparContato)
                    .addComponent(BtExcluirContato)
                    .addComponent(btAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JScrollTabelaContato, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RdPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdPessoaJuridicaActionPerformed
        RdPessoaJuridica.setEnabled(true);
        LbCpfCnpj.setText("CNPJ");
        RdPessoaFisica.setEnabled(false);
        RdPessoaFisica.setSelected(false);
    }//GEN-LAST:event_RdPessoaJuridicaActionPerformed

    private void BtLimparContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimparContatoActionPerformed
        TxtNome.setText("");
        TxtCpfCnpj.setText("");
        TxtTelefone.setText("");
        TxtEmail.setText("");
        LbCpfCnpj.setText("CPF-CNPJ");
    }//GEN-LAST:event_BtLimparContatoActionPerformed

    private void BtSalvaContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvaContatoActionPerformed

        if (RdPessoaFisica.isSelected() && RdPessoaJuridica.isSelected()) {
            System.out.println("erro"); // arrumar
        } else {
            if (TxtNome.getText().equals("") || TxtEmail.getText().equals("") || TxtCpfCnpj.getText().equals("") || TxtTelefone.getText().equals("")) {
                System.out.println("erro"); // arrumar
            } else {
                String nome, codigo, telefone, email;
                telefone = TxtTelefone.getText();
                email = TxtEmail.getText();
                Contato contato = new Contato(email, telefone);
                nome = TxtNome.getText();
                codigo = TxtCpfCnpj.getText();
                if (RdPessoaFisica.isSelected()) {
                    PessoaFisica pessoa = new PessoaFisica(nome, codigo);
                    pessoa.setContato(contato);
                    agenda.addPessoa(pessoa);
                } else {
                    PessoaJuridica pessoa = new PessoaJuridica(nome, codigo);
                    pessoa.setContato(contato);
                    agenda.addPessoa(pessoa);
                }

            }
        }
        DefaultTableModel dtb = (DefaultTableModel) TbPessoa.getModel();
        Object[] pessoas = {TxtNome.getText(), TxtTelefone.getText(), TxtEmail.getText(), TxtCpfCnpj.getText()};
        dtb.addRow(pessoas);
        BtNovoContatoActionPerformed(evt);

    }//GEN-LAST:event_BtSalvaContatoActionPerformed

    private void BtNovoContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoContatoActionPerformed
        RdPessoaFisica.setEnabled(true);
        RdPessoaJuridica.setEnabled(true);
        RdPessoaJuridica.setSelected(false);
        RdPessoaFisica.setSelected(false);
        BtLimparContatoActionPerformed(evt);

    }//GEN-LAST:event_BtNovoContatoActionPerformed

    private void RdPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdPessoaFisicaActionPerformed
        RdPessoaFisica.setEnabled(true);
        LbCpfCnpj.setText("CPF");
        RdPessoaJuridica.setSelected(false);
        RdPessoaJuridica.setEnabled(false);
    }//GEN-LAST:event_RdPessoaFisicaActionPerformed

    private void BtExcluirContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirContatoActionPerformed
        if (TbPessoa.getSelectedRow() != -1) {
            DefaultTableModel dtb = (DefaultTableModel) TbPessoa.getModel();
            dtb.removeRow(TbPessoa.getSelectedRow());
            BtNovoContatoActionPerformed(evt);
        }
    }//GEN-LAST:event_BtExcluirContatoActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        if (TbPessoa.getSelectedRow() != -1) {
            TbPessoa.setValueAt(TxtNome.getText(), TbPessoa.getSelectedRow(), 0);
            TbPessoa.setValueAt(TxtTelefone.getText(), TbPessoa.getSelectedRow(), 1);
            TbPessoa.setValueAt(TxtEmail.getText(), TbPessoa.getSelectedRow(), 2);
            TbPessoa.setValueAt(TxtCpfCnpj.getText(), TbPessoa.getSelectedRow(), 3);
        }

    }//GEN-LAST:event_btAlterarActionPerformed

    private void TbPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbPessoaMouseClicked
        if (TbPessoa.getSelectedRow() != -1) {
            TxtNome.setText((String) TbPessoa.getValueAt(TbPessoa.getSelectedRow(), 0));
            TxtTelefone.setText((String) TbPessoa.getValueAt(TbPessoa.getSelectedRow(), 1));
            TxtEmail.setText((String) TbPessoa.getValueAt(TbPessoa.getSelectedRow(), 2));
            TxtCpfCnpj.setText((String) TbPessoa.getValueAt(TbPessoa.getSelectedRow(), 3));

        }
    }//GEN-LAST:event_TbPessoaMouseClicked

    private void TbPessoaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TbPessoaKeyReleased
        if (TbPessoa.getSelectedRow() != -1) {
            TxtNome.setText((String) TbPessoa.getValueAt(TbPessoa.getSelectedRow(), 0));
            TxtEmail.setText((String) TbPessoa.getValueAt(TbPessoa.getSelectedRow(), 2));
            TxtCpfCnpj.setText((String) TbPessoa.getValueAt(TbPessoa.getSelectedRow(), 3));
            TxtTelefone.setText((String) TbPessoa.getValueAt(TbPessoa.getSelectedRow(), 1));
        }
    }//GEN-LAST:event_TbPessoaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtExcluirContato;
    private javax.swing.JButton BtLimparContato;
    private javax.swing.JButton BtNovoContato;
    private javax.swing.JButton BtSalvaContato;
    private javax.swing.JScrollPane JScrollTabelaContato;
    private javax.swing.JLabel LbCpfCnpj;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbTelefone;
    private javax.swing.JRadioButton RdPessoaFisica;
    private javax.swing.JRadioButton RdPessoaJuridica;
    private javax.swing.JTable TbPessoa;
    private javax.swing.JTextField TxtCpfCnpj;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtTelefone;
    private javax.swing.JToggleButton btAlterar;
    // End of variables declaration//GEN-END:variables
}
